const colors = {
  MAIN: "#5DAA8F",
  BACKGROUND: "#F7EEDB",
  SUB: "#F2A65A",
  SUB_FONT: "#754D26",
  MAIN_FONT: "#1D2027",
  WHITE: "#FFFFFF",
  YELLOW: "#FEE500",
  RED: "#FF0009",
  GRAY: "#999999",
  GRAY_50: "#F8F9FA",
  GRAY_50_TINT: "#F5F6F8",
  GREEN: "#00B505",
  NEON_GREEN_50: "#E8FFE4",
  NEUTRAL_DARK_LIGHT: "#71727A",
  NEUTRAL_DARK_DARKEST: "#1F2024",
  SLATE_TINT_5: "#7176800D",
  SLATE_TINT_10: "#7176801A",
  SLATE_50: "#F8F9FB",
  SLATE_200: "#DBDEE3",
  SLATE_300: "#BCC0C6",
  SLATE_400: "#9FA3AB",
  SLATE_500: "#717680",
  SLATE_600: "#4B515B",
  SLATE_700: "#24282F",
  SLATE_800: "#1D2027",
  CU_GREEN: "#A5CF4C",
  CU_PURPLE: "#693B97",
  GS_ORANGE: "#CC6600",
  GS_GREEN: "#009999",
  EMART_YELLOW: "#FFB718",
  EMART_DARK_GRAY: "#55555A",
  SEVEN_ELEVEN_GREEN: "#009739",
  SEVEN_ELEVEN_ORANGE: "#F36F21",
  NEUTRAL_LIGHT_MEDIUM: "#E8E9F1",
  ERROR_BG: "#FFF5F5",
  ERROR_BORDER: "#E57373",
  ERROR_TEXT: "#D32F2F",
};

const fontMap = {
  ryurue: require("@/assets/fonts/ryurue.ttf"),
  regular: require("@/assets/fonts/Pretendard-Regular.ttf"),
  medium: require("@/assets/fonts/Pretendard-Medium.ttf"),
  semiBold: require("@/assets/fonts/Pretendard-SemiBold.ttf"),
  bold: require("@/assets/fonts/Pretendard-Bold.ttf"),
};

const fonts = {
  RYURUE: "ryurue",
  REGULAR: "regular",
  MEDIUM: "medium",
  SEMI_BOLD: "semiBold",
  BOLD: "bold",
} as const;

const icons = {
  home: "material-symbols-light:home-rounded",
  homeOutline: "material-symbols-light:home-outline-rounded",
  search: "circum:search",
  person: "material-symbols-light:person-rounded",
  personOutline: "material-symbols-light:person-outline-rounded",
  heartLight: "ph:heart-light",
  heartFill: "ph:heart-fill",
  alert: "fluent:alert-20-regular",
  location: "material-symbols-light:location-on",
  locationOutline: "material-symbols-light:location-on-outline",
  downSquare: "icon-park-outline:down-square",
  upSquare: "icon-park-outline:up-square",
  chevronRightLine: "material-symbols-light:chevron-right-rounded",
  chevronLeftLine: "material-symbols-light:chevron-left-rounded",
  share: "fluent:share-ios-20-regular",
  filledStar: "solar:star-bold",
  expandLess: "si:expand-less-alt-line",
  expandMore: "si:expand-more-alt-line",
  info: "material-symbols-light:info-outline-rounded",
  receiptOutline: "material-symbols-light:receipt-outline-rounded",
  thumbsUp: "carbon:thumbs-up",
  thumbsUpFill: "carbon:thumbs-up-filled",
  addRounded: "material-symbols-light:add-rounded",
  xCircleFill: "ph:x-circle-fill",
  checkCircle: "material-symbols-light:check-circle-rounded",
  circleOutline: "material-symbols-light:circle-outline",
  check: "material-symbols-light:check-rounded",
};

export { colors, fontMap, fonts, icons };
